# ----> ITALIAN <----
# Leggere 7 valori interi da input e calcolarne 
# la media (stampandola a video).
# INPUT
# 12;
# 82;
# 11;
# 2345;
# 67;
# 123456;
# 675
# OUTPUT
# 126069.428571428

NB: La media deve essere espressa con un numero reale (float). Utilizzare il coprocessore matematico.
.text
.globl main
main:	
	li $v0,5 # CHIEDO UN NUMERO IN INPUT
	syscall
	move $t0,$v0
	li $v0,5 # CHIEDO UN NUMERO IN INPUT
	syscall
	move $t1,$v0
	li $v0,5 # CHIEDO UN NUMERO IN INPUT
	syscall
	move $t2,$v0
	li $v0,5 # CHIEDO UN NUMERO IN INPUT
	syscall
	move $t3,$v0
	li $v0,5 # CHIEDO UN NUMERO IN INPUT
	syscall
	move $t4,$v0
	li $v0,5 # CHIEDO UN NUMERO IN INPUT
	syscall
	move $t5,$v0
	li $v0,5 # CHIEDO UN NUMERO IN INPUT
	syscall
	move $t6,$v0
	
	li $t7,7 # CARICO IN t7 IL VALORE 7 OVVERO IL NUMERO DI NUMERI 

	mtc1 $t0,$f0 # CONVERTO IL NUMERO INTERO IN NUMERO REALE (FLOAT) USANDO IL COPROCESSORE MATEMATICO
	cvt.s.w $f0,$f0
	mtc1 $t1,$f1 # CONVERTO IL NUMERO INTERO IN NUMERO REALE (FLOAT) USANDO IL COPROCESSORE MATEMATICO
	cvt.s.w $f1,$f1
	mtc1 $t2,$f2 # CONVERTO IL NUMERO INTERO IN NUMERO REALE (FLOAT) USANDO IL COPROCESSORE MATEMATICO
	cvt.s.w $f2,$f2
	mtc1 $t3,$f3 # CONVERTO IL NUMERO INTERO IN NUMERO REALE (FLOAT) USANDO IL COPROCESSORE MATEMATICO
	cvt.s.w $f3,$f3
	mtc1 $t4,$f4 # CONVERTO IL NUMERO INTERO IN NUMERO REALE (FLOAT) USANDO IL COPROCESSORE MATEMATICO
	cvt.s.w $f4,$f4
	mtc1 $t5,$f5 # CONVERTO IL NUMERO INTERO IN NUMERO REALE (FLOAT) USANDO IL COPROCESSORE MATEMATICO
	cvt.s.w $f5,$f5
	mtc1 $t6,$f6 # CONVERTO IL NUMERO INTERO IN NUMERO REALE (FLOAT) USANDO IL COPROCESSORE MATEMATICO
	cvt.s.w $f6,$f6
	mtc1 $t7,$f8 # CONVERTO IL NUMERO INTERO IN NUMERO REALE (FLOAT) USANDO IL COPROCESSORE MATEMATICO
	cvt.s.w $f8,$f8

	add.s $f7,$f0,$f1 # SOMMA FLOATING POINT A SINGOLA PRECISIONE
	add.s $f7,$f7,$f2 # SOMMA FLOATING POINT A SINGOLA PRECISIONE
	add.s $f7,$f7,$f3 # SOMMA FLOATING POINT A SINGOLA PRECISIONE
	add.s $f7,$f7,$f4 # SOMMA FLOATING POINT A SINGOLA PRECISIONE
	add.s $f7,$f7,$f5 # SOMMA FLOATING POINT A SINGOLA PRECISIONE
	add.s $f7,$f7,$f6 # SOMMA FLOATING POINT A SINGOLA PRECISIONE

	div.s $f9,$f7,$f8 # DIVISIONE FLOATING POINT A SINGOLA PRECISIONE

	mov.s $f12,$f9 # SPOSTO IL RISULTATO DELLA DIVISIONE IN f12 E STAMPO IL VALORE SU CONSOLE
	li $v0,2
	syscall
	li $v0,10 # FINE PROGRAMMA
	syscall

.data
